server:
  port: 8890

spring:
  application:
    name: Spring_Boot_Demo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bnz_edu?useUnicode=true&characterEncoding=gbk&autoReconnect=true&failOverReadOnly=false
    username: root
    password: root
  redis:
    database: 0  # Redis服务器地址
    host: 127.0.0.1 # Redis服务器连接端口
    port: 6379  # Redis服务器连接密码（默认为空）
    timeout: 1000  # 连接超时时间（毫秒）
  thymeleaf:
    cache: false
#    lettuce:
#      pool:
#        max-active: 200 # 连接池最大连接数（使用负值表示没有限制）
#        max-wait: -1  # 连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-idle: 10  # 连接池中的最大空闲连接
#        min-idle: 0  # # 连接池中的最小空闲连接


