server:
  port: 8890

spring:
  application:
    name: Spring_Boot_Demo
  messages:
    basename: i18n.login  # 获取国际化配置文件位置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bnz_edu?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&autoReconnect=true
    username: root
    password: root
  redis:
    database: 0  # Redis服务器地址
    host: 127.0.0.1 # Redis服务器连接端口
    port: 6379  # Redis服务器连接密码（默认为空）
    timeout: 1000  # 连接超时时间（毫秒）
  thymeleaf:
    cache: false
#    lettuce:
#      pool:
#        max-active: 200 # 连接池最大连接数（使用负值表示没有限制）
#        max-wait: -1  # 连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-idle: 10  # 连接池中的最大空闲连接
#        min-idle: 0  # # 连接池中的最小空闲连接
logging:
  level:
    com.neo: debug
mybatis-plus:
  # MyBaits 别名包扫描路径，通过该属性可以给包中的类注册别名
  type-aliases-package: com.example.zero.model.*
  # 该配置请和 typeAliasesPackage 一起使用，如果配置了该属性，则仅仅会扫描路径下以该类作为父类的域对象 。
  type-aliases-super-type: java.lang.

  configuration:
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 驼峰下划线转换
    map-underscore-to-camel-case: true
    # 配置的缓存的全局开关
    cache-enabled: true
    # 延时加载的开关
    lazy-loading-enabled: true
    # 开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
    multiple-result-sets-enabled: true
    use-generated-keys: true
    default-statement-timeout: 60
    default-fetch-size: 100
